sudo: false
dist: trusty

language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master
    - develop

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - LOCAL_DIR: build
    - COMPOSER_INSTALL: true
    - NPM_INSTALL: false
    - WP_INSTALL: false

matrix:
  include:
  - env:  WP_TRAVISCI=lint:php COMPOSER_INSTALL=true NPM_INSTALL=false WP_INSTALL=false
    name: PHP Linting

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
      phpenv config-rm xdebug.ini
    else
      echo "xdebug.ini does not exist"
    fi
  - |
    if [[ "$WP_TRAVISCI" == "lint:php" ]] ; then
    composer install
      composer global require wp-coding-standards/wpcs,phpcompatibility/php-compatibility
      phpcs --config-set installed_paths $HOME/.composer/vendor/wp-coding-standards/wpcs,$HOME/.composer/vendor/phpcompatibility/php-compatibility
    fi

script:
  - |
    if [[ "$WP_TRAVISCI" == "lint:php" ]] ; then
      phpcs --show-config
    fi
