sudo: false
dist: trusty

language: php
php:
  - 7.0

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master
    - develop

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - LOCAL_DIR: build
    - COMPOSER_INSTALL: true
    - NPM_INSTALL: false
    - WP_INSTALL: false

matrix:
  include:
  - env:  WP_TRAVISCI=lint:php COMPOSER_INSTALL=true NPM_INSTALL=false WP_INSTALL=false
    name: PHP Linting

before_script:
  - composer install
  - export PATH="$HOME/.composer/vendor/bin:$PATH"

script:
  - |
    if [[ "$WP_TRAVISCI" == "lint:php" ]] ; then
      vendor/bin/phpcs --basepath=./ --report-json=phpcs-report.json --report-source .
    fi
