sudo: false
dist: trusty

language: php
php:
  - 7.2

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master
    - develop

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - LOCAL_DIR: build
    - COMPOSER_INSTALL: true
    - NPM_INSTALL: false
    - WP_INSTALL: false

matrix:
  include:
  - env:  WP_TRAVISCI=lint:php COMPOSER_INSTALL=true NPM_INSTALL=false WP_INSTALL=false
    name: PHP Linting

before_script:
  - composer install
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - which composer
  - ./vendor/bin/phpcs --version
  # - which phpcs
  # - |
  #   if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
  #     phpenv config-rm xdebug.ini
  #   else
  #     echo "xdebug.ini does not exist"
  #   fi
  - |
    if [[ "$WP_TRAVISCI" == "lint:php" ]] ; then
      composer global require "squizlabs/php_codesniffer=*,wp-coding-standards/wpcs=*,phpcompatibility/php-compatibility=*"
      phpcs --config-set installed_paths $HOME/.composer/vendor/wp-coding-standards/wpcs,$HOME/.composer/vendor/phpcompatibility/php-compatibility
    fi

script:
  - |
    if [[ "$WP_TRAVISCI" == "lint:php" ]] ; then
      phpcs .
    fi
